version: '2'
services:
    myjhipsterapp-app:
        image: myjhipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myjhipsterapp-mysql:3306/myjhipsterapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myjhipsterapp-mysql:
        extends:
            file: mysql.yml
            service: myjhipsterapp-mysql
